### ISSUE TITLE
Support Libplanet logging using Serilog

### ISSUE THREAD

**Issue by greymistcube** [planetarium/UniLibplanet#30]
It's probably a good idea to add some rudimentary `Serilog.Sinks` such as `Serilog.Sinks.Console` and maybe `Serilog.Sinks.File` as dependency so that it is easily configurable to capture [Libplanet] logs for debugging. 😗

[Libplanet]: https://github.com/planetarium/libplanet

**Comment by kugorang** [comment]
Hi, Hello
