### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by greymistcube** [planetarium/UniLibplanet#59]
On development branch, [libplanet] has been bumped to 0.39.0. Release 0.6.0.

[libplanet]: https://github.com/planetarium/libplanet

**Comment by greymistcube** [comment]
Things to do:
- [ ] Build new `UniLibplanet.untiypackage` from 54fc97c on development branch.
- [ ] Test the build using new `UniLibplanet.unitypackage` instead of `0.5.0` release with [Basic Node tutorial].
- [ ] Merge development branch onto main.
- [ ] Tag main with `0.6.0`.

**Comment by KimDaeYu** [comment]
Assignees

**Comment by greymistcube** [comment]
Closed by #61.
